---
authors:
  - evajust
dependencies:
  "ansible.utils": ">=3.0.0"
license_file: LICENSE
name: kbd_interactive
namespace: evajust
description:
  Collection to handle keyboard interactive auth with paramiko for network
  devices.
readme: README.md
repository: https://github.com/evajust/kbd_interactive
issues: https://github.com/evajust/kbd_interactive/issues
tags: [networking, kbd_interactive, keyboard]
version: 0.0.1
